// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKQIRH4MV_iesw64LHkX5HvjYDV9tpe-c',
    appId: '1:987908346610:web:3d02931b3fd327f678366b',
    messagingSenderId: '987908346610',
    projectId: 'auth-16988',
    authDomain: 'auth-16988.firebaseapp.com',
    storageBucket: 'auth-16988.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhBjFJvzI6f3IyEpK_O7RJ-JBU2bsvHmk',
    appId: '1:987908346610:android:73fd51c7a3d1e76d78366b',
    messagingSenderId: '987908346610',
    projectId: 'auth-16988',
    storageBucket: 'auth-16988.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBplHLwX6evA-jl43TpAzWX4XvL-oF06dI',
    appId: '1:987908346610:ios:11df432f5ae520c678366b',
    messagingSenderId: '987908346610',
    projectId: 'auth-16988',
    storageBucket: 'auth-16988.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
